import {
  Palette, Scissors, UtensilsCrossed, ShoppingBag, Camera, Wrench,
  Gem, Heart, Flower2, Coffee, Briefcase, Shirt,
} from 'lucide-react'

export const BUSINESS_TYPES = {
  tattoo: {
    id: 'tattoo',
    name: 'Tattoo Studio',
    icon: Palette,
    accent: 'purple',
    terminology: {
      orders: 'Sessioni',
      order: 'Sessione',
      inventory: 'Materiali',
      product: 'Design',
      products: 'Design',
      calendar: 'Appuntamenti',
      event: 'Appuntamento',
      contacts: 'Clienti',
      contact: 'Cliente',
    },
    defaultCategories: ['Tattoo', 'Piercing', 'Cover-up', 'Ritocco', 'Consultazione'],
    orderStatuses: ['Richiesta', 'Bozzetto', 'Approvato', 'In corso', 'Completato', 'Guarigione'],
    features: { deposits: true, gallery: true, consent: true },
  },
  restaurant: {
    id: 'restaurant',
    name: 'Ristorante / Food',
    icon: UtensilsCrossed,
    accent: 'orange',
    terminology: {
      orders: 'Ordini',
      order: 'Ordine',
      inventory: 'Magazzino',
      product: 'Piatto',
      products: 'Menu',
      calendar: 'Prenotazioni',
      event: 'Prenotazione',
      contacts: 'Clienti',
      contact: 'Cliente',
    },
    defaultCategories: ['Antipasti', 'Primi', 'Secondi', 'Dolci', 'Bevande', 'Asporto'],
    orderStatuses: ['Ricevuto', 'In preparazione', 'Pronto', 'In consegna', 'Consegnato', 'Annullato'],
    features: { delivery: true, tables: true, menu: true },
  },
  artisan: {
    id: 'artisan',
    name: 'Artigiano',
    icon: Wrench,
    accent: 'amber',
    terminology: {
      orders: 'Commesse',
      order: 'Commessa',
      inventory: 'Materiali',
      product: 'Prodotto',
      products: 'Prodotti',
      calendar: 'Scadenze',
      event: 'Scadenza',
      contacts: 'Clienti',
      contact: 'Cliente',
    },
    defaultCategories: ['Legno', 'Ceramica', 'Pelle', 'Tessuto', 'Metallo', 'Personalizzato'],
    orderStatuses: ['Richiesta', 'Preventivo', 'Confermato', 'In lavorazione', 'Pronto', 'Consegnato'],
    features: { quotes: true, materials: true, customization: true },
  },
  beauty: {
    id: 'beauty',
    name: 'Beauty / Parrucchiere',
    icon: Scissors,
    accent: 'pink',
    terminology: {
      orders: 'Servizi',
      order: 'Servizio',
      inventory: 'Prodotti',
      product: 'Prodotto',
      products: 'Prodotti',
      calendar: 'Appuntamenti',
      event: 'Appuntamento',
      contacts: 'Clienti',
      contact: 'Cliente',
    },
    defaultCategories: ['Taglio', 'Colore', 'Trattamento', 'Manicure', 'Pedicure', 'Massaggio'],
    orderStatuses: ['Prenotato', 'Confermato', 'In corso', 'Completato', 'No-show'],
    features: { bookings: true, loyalty: true, reminders: true },
  },
  jewelry: {
    id: 'jewelry',
    name: 'Gioielleria',
    icon: Gem,
    accent: 'teal',
    terminology: {
      orders: 'Ordini',
      order: 'Ordine',
      inventory: 'Collezione',
      product: 'Gioiello',
      products: 'Gioielli',
      calendar: 'Scadenze',
      event: 'Scadenza',
      contacts: 'Clienti',
      contact: 'Cliente',
    },
    defaultCategories: ['Anelli', 'Collane', 'Bracciali', 'Orecchini', 'Personalizzati', 'Riparazioni'],
    orderStatuses: ['Richiesta', 'Design', 'In lavorazione', 'Pronto', 'Consegnato'],
    features: { customization: true, certificates: true, sizing: true },
  },
  photography: {
    id: 'photography',
    name: 'Fotografia',
    icon: Camera,
    accent: 'blue',
    terminology: {
      orders: 'Progetti',
      order: 'Progetto',
      inventory: 'Attrezzatura',
      product: 'Servizio',
      products: 'Servizi',
      calendar: 'Sessioni',
      event: 'Sessione',
      contacts: 'Clienti',
      contact: 'Cliente',
    },
    defaultCategories: ['Matrimonio', 'Ritratto', 'Evento', 'Prodotto', 'Food', 'Moda'],
    orderStatuses: ['Richiesta', 'Preventivo', 'Confermato', 'Shooting', 'Post-produzione', 'Consegnato'],
    features: { gallery: true, contracts: true, deliverables: true },
  },
  fashion: {
    id: 'fashion',
    name: 'Moda / Sartoria',
    icon: Shirt,
    accent: 'red',
    terminology: {
      orders: 'Ordini',
      order: 'Ordine',
      inventory: 'Tessuti',
      product: 'Capo',
      products: 'Capi',
      calendar: 'Prove',
      event: 'Prova',
      contacts: 'Clienti',
      contact: 'Cliente',
    },
    defaultCategories: ['Abiti', 'Camicie', 'Pantaloni', 'Giacche', 'Accessori', 'Riparazioni'],
    orderStatuses: ['Misure', 'Taglio', 'Cucitura', 'Prova', 'Rifiniture', 'Pronto'],
    features: { measurements: true, fittings: true, customization: true },
  },
  generic: {
    id: 'generic',
    name: 'Altro',
    icon: Briefcase,
    accent: 'blue',
    terminology: {
      orders: 'Ordini',
      order: 'Ordine',
      inventory: 'Magazzino',
      product: 'Prodotto',
      products: 'Prodotti',
      calendar: 'Calendario',
      event: 'Evento',
      contacts: 'Contatti',
      contact: 'Contatto',
    },
    defaultCategories: ['Categoria 1', 'Categoria 2', 'Categoria 3'],
    orderStatuses: ['Nuovo', 'In lavorazione', 'Completato', 'Annullato'],
    features: {},
  },
}

export function getBusinessType(id) {
  return BUSINESS_TYPES[id] || BUSINESS_TYPES.generic
}

export function getTerminology(businessTypeId, key) {
  const bt = getBusinessType(businessTypeId)
  return bt.terminology[key] || key
}
